### ISSUE TITLE
500 Error when viewing stats

### ISSUE THREAD

**Issue by mattcadorette** [rashidkpc/kibana2#123] opened 2012-10-30 17:09 UTC
I just started trying Kibana, and so far I love it.  The only issue I am having is the stats button doesn't work.  When I click it I get:

Oops! Something went terribly wrong.
I'm not totally sure what happened, but maybe refreshing, or hitting Reset will help. If that doesn't work, you can try restarting your browser. If all else fails, it is possible your configuation has something funky going on. 

If it helps, I received a 500 Internal Server Error from: api/analyze/@fields.syslog_facility/mean/eyJzZWFyY2giOiIiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6OTAwLCJncmFwaG1vZGUiOiJjb3VudCIsInRpbWUiOnsidXNlcl9pbnRlcnZhbCI6MH0sIm1vZGUiOiJtZWFuIiwiYW5hbHl6ZV9maWVsZCI6IkBmaWVsZHMuc3lzbG9nX2ZhY2lsaXR5In0=?_=1351616895662

Not sure if I am missing a dependency or something, however I did install all software documented in the readme.

**Comment by mattcadorette** [comment] 2012-10-30 17:35
The output from kibana.rb:

 [30/Oct/2012 13:27:57] "GET /api/graph/count/10000/eyJzZWFyY2giOiIiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6OTAwLCJncmFwaG1vZGUiOiJjb3VudCJ9/?_=1351618077949 HTTP/1.1" 200 3449 0.0174
X.X.X.X - - [30/Oct/2012 13:28:00] "GET /images/ajax-loader.gif HTTP/1.1" 304 - 0.0019
NoMethodError - undefined method `[]' for nil:NilClass:
        ./lib/kelastic.rb:111:in`field_type'
        kibana.rb:204:in `GET /api/analyze/:field/mean/:hash'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in`call'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in `compile!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in`[]'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in`route_eval'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in`process_route'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `catch'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in`process_route'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `route!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in`each'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in`dispatch!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`invoke'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `catch'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`invoke'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in`call'
        /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
        /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in`call'
        /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in`call'
        /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
        /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
        /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
        /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in`call'
        /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
        /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in`call_without_check'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:136:in `call'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:129:in`call'
        /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
        /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in`call'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in`call'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1471:in`synchronize'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
        /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:81:in`pre_process'
        /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
        /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in`pre_process'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in `call'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in`spawn_threadpool'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in `initialize'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in`new'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in `spawn_threadpool'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1023:in`defer'
        /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:51:in `process'
        /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:39:in`receive_data'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
        /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run'
        /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
        /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/server.rb:159:in`start'
        /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/handler/thin.rb:13:in `run'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in`run!'
        /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/main.rb:25
        kibana.rb:307

**Comment by TheGU** [comment] 2012-10-31 02:34
I found exactly the same problem as this one. 
For configuration
on logstash I follow this example : http://logstash.net/docs/1.1.4/tutorials/getting-started-simple
for Kibana I just extract and run.
Everything work fine except when you click on stats button on the left fields.

**Comment by rashidkpc** [comment] 2012-10-31 04:46
Looks like this is caused by kibana being unable to determine the type of the field requested. I'll investigate adding more error correction tomorrow. Do you experience this on every field? Or only syslog_facility?

**Comment by TheGU** [comment] 2012-10-31 12:04
Confirm that this error happen on every fields.

**Comment by jmilburn** [comment] 2012-10-31 14:30
I just installed/configured logstash/redis/elasticsearch/kibana yesterday and am also seeing this. Happens on every field for me also.

**Comment by awheeler** [comment] 2012-10-31 15:31
I have Identified the cause: in the file lib/kelastic.rb, in the collect_item_attributes function, the r array must be returned explicitly.
A fix should be forthcoming.

**Comment by rashidkpc** [comment] 2012-10-31 19:01
What version of ES is this happening on?

**Comment by awheeler** [comment] 2012-10-31 20:07
I'm using elasticsearch-0.19.10-1.

**Comment by mattcadorette** [comment] 2012-10-31 20:51
0.19.10

**Comment by rashidkpc** [comment] 2012-10-31 22:30
Just committed ahweeler's potential fix, however I haven't been able to replicate this issue personally. Can someone give it a go?

**Comment by mattcadorette** [comment] 2012-10-31 22:44
That fixed it for me, I can now view stats on numeric values --- thanks!

**Comment by rashidkpc** [comment] 2012-10-31 22:48
Rad, thanks awheeler Closing this

**Closed as completed by rashidkpc** 2012-10-31 22:48 UTC

**Comment by jmilburn** [comment] 2012-11-19 10:28
I have applied the fix and it appears to work for most of them, and we get "Statistical analysis unavailable for @message back to logs - I'm not able to analyze @message. Statistical analysis is only available for fields that are stored a number (eg float, int) in ElasticSearch", which is fine as we are still configuring this.

However, it is still not working for "@tags" and we get the errors below. Not sure if everyone has checked this and it may not be something we use but getting a 500 error is never ideal.

Kibana error - If it helps, I received a 500 Internal Server Error from: api/analyze/@tags/mean/eyJzZWFyY2giOiJtb2JpbGUiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6IjE0NDAwIiwiZ3JhcGhtb2RlIjoiY291bnQiLCJ0aW1lIjp7InVzZXJfaW50ZXJ2YWwiOjB9LCJzdGFtcCI6MTM1MzMxOTc3NzUwOSwibW9kZSI6Im1lYW4iLCJhbmFseXplX2ZpZWxkIjoiQHRhZ3MifQ==?_=1353320847690

Kibana log error -

NoMethodError - undefined method `[]' for nil:NilClass:
    ./lib/kelastic.rb:111:in`field_type'
    kibana.rb:204:in `GET /api/analyze/:field/mean/:hash'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `[]'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in`route!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in `route_eval'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in`route!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in `process_route'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in`catch'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `process_route'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in`route!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `each'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in`route!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in`catch'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in`call!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in`context'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/logger.rb:15:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call_without_check'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:136:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:129:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in `call'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1471:in `synchronize'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:81:in `pre_process'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in`catch'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in`call'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in `spawn_threadpool'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in`initialize'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in `new'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in`spawn_threadpool'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1023:in `defer'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:51:in`process'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in`start'
    /usr/local/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    /usr/local/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/handler/thin.rb:13:in`run'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in `run!'
    /usr/local/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/main.rb:25
    kibana.rb:307
84.19.53.21 - - [19/Nov/2012 10:11:58]
