### ISSUE TITLE
No data in IE or Chrome?

### ISSUE THREAD

**Issue by bschrock** [rashidkpc/kibana2#362] opened 2013-05-29 13:37 UTC
Is anyone else noticing that Chrome and IE do not show data anymore? I installed the update for Chrome and now I do not get any data showing up. I can see data using Firefox v21 and Opera 12.15 on Win7 32-bit, but I cannot see any data on the other major browsers. Is anyone else having this problem?

Brian,

**Comment by fpeterschmitt** [comment] 2013-05-29 14:26
Yes, I've just seen the problem 5 minutes ago. Searching everywhere but the browser, it works with Firefox but not with Chrome and IE.

**Comment by bschrock** [comment] 2013-05-30 13:56
Looks like this might be the problem?

Caught this in Chrome developer tools:

```
Refused to execute script from 'http://kibana.aws.ecnext.net:5601/js/timezone.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled. kibana.aws.ecnext.net/:1
Uncaught ReferenceError: tOffset is not defined 
```

Also when I use git to update to master it works.

**Comment by ajardan** [comment] 2013-05-31 08:15
Same thing, cannot view any data in latest Chrome, the page just keeps "loading"

**Comment by mikedougherty** [comment] 2013-06-04 18:09
@bschrock is correct - the `tOffset` variable is not defined at the point that `CreateLogTable` is called. 

A non-trivial workaround is to use Chrome developer tools to enable a breakpoint before the exception occurs (~ ajax.js:958) and when the breakpoint gets hit, run `window.tOffset = 0;` in the console. Then, unset the breakpoint and resume execution. Kibana should work until the next page load.

**Comment by lnxmachine** [comment] 2013-06-04 19:55
Dirty workaround, copy the contents of the /js/timezone.js from inside the chrome console (click the link it shows the contents), create a timezone.js file inside public/lib/js with the contents of the generated timzone.js.  Edit the index.html in the root of public, change the path to timezone.js:

<script type="text/javascript" src="lib/js/timezone.js"></script>

I don't  know anything about ruby, so I'm not sure how to fix the issue, but this allowed it to work again in Chrome until a fix is found.  I assume this probably breaks things for folks in different timezones.

**Comment by cakirke** [comment] 2013-06-06 20:12
confirming i've seen this in Chrome on Windows and Mac, unsuccessful with lnxmachine's workaround

**Comment by JamesDooley** [comment] 2013-06-15 14:08
It looks like this is due to the timezone.erb file not setting the mime type (or more specifically the kibana.rb file).

It does look like there was a patch submitted about 5 months ago that has not been merged in yet:
https://github.com/goncha/Kibana/commit/8ffae5423547709228d65ef6d3d5754cae40f3e6

If you edit that line in the kibana.rb file and restart kibana you should be able to access the site using Chrome (and IE?)

**Comment by rashidkpc** [comment] 2013-06-16 15:52
I've not been able to replicate this in Chrome 27.0.1453.110, but I went ahead and made the change sugested by 8ffae54.

**Comment by JamesDooley** [comment] 2013-06-16 22:31
Also looking at commit: https://github.com/rashidkpc/Kibana/commit/edae3863571f84ef80416527c1966b666022d482
It looks like you are calling erb :timezone twice now instead of just once. 

Thanks for getting the fix pushed out Rashid.

**Comment by rashidkpc** [comment] 2013-06-16 23:34
Fix again, doh. Let me know if that works

**Comment by cakirke** [comment] 2013-06-17 14:57
confirmed working on OSX 10.8.4/Chrome 27.0.1453.110

**Closed as completed** 2013-06-17 17:29 UTC
